# Generated by Django 5.2.16 on 2026-07-12 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('text', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'About Chip',
                'verbose_name_plural': '👤 About Section — Skill Chips',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='About', max_length=100)),
                ('heading', models.CharField(default='A short headline about what you build.', max_length=200)),
                ('paragraph_intro', models.TextField(default='An opening paragraph, bold and short.')),
                ('paragraph_body', models.TextField(blank=True, default="More detail about your background, what you've built, and what you're doing now.")),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': '👤 About Section — Text',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('icon', models.CharField(choices=[('linkedin', 'LinkedIn'), ('email', 'Email'), ('phone', 'Phone'), ('location', 'Location'), ('github', 'GitHub'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(help_text="e.g. 'LinkedIn — in/your-handle'", max_length=150)),
                ('link', models.CharField(help_text="e.g. 'https://linkedin.com/in/you', 'mailto:you@example.com', 'tel:+91...'", max_length=300)),
            ],
            options={
                'verbose_name': 'Contact Info Line',
                'verbose_name_plural': '✉️ Contact — Info Lines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Contact', max_length=100)),
                ('heading', models.CharField(default="Let's build something great.", max_length=200)),
                ('lede', models.TextField(blank=True, default='Open to new roles and freelance projects.')),
                ('form_note', models.CharField(default='Opens your email client with this message pre-filled — no data leaves your browser.', max_length=200)),
                ('mailto_address', models.EmailField(default='you@example.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': '✉️ Contact — Section Text',
            },
        ),
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('year_range', models.CharField(help_text="e.g. '2016 – 2020'", max_length=60)),
                ('degree', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Education Item',
                'verbose_name_plural': '🎓 Education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('role_title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('date_range', models.CharField(help_text="e.g. 'Jan 2026 — Present'", max_length=80)),
                ('location_meta', models.CharField(blank=True, help_text="e.g. 'Remote · 7 mos'", max_length=120)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': '💼 Experience — Timeline Entries',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Backend Engineering · Since 2020', max_length=100)),
                ('full_name', models.CharField(default='Your Name', max_length=150)),
                ('role_title', models.CharField(default='Senior Python Django Developer', max_length=200)),
                ('description', models.TextField(default='A short, punchy description of what you do and who you do it for.')),
                ('location', models.CharField(default='Your City, Your Country', max_length=150)),
                ('primary_button_text', models.CharField(default='Get in touch', max_length=40)),
                ('primary_button_link', models.CharField(default='#contact', max_length=100)),
                ('secondary_button_text', models.CharField(default='View experience', max_length=40)),
                ('secondary_button_link', models.CharField(default='#experience', max_length=100)),
                ('ledger_title', models.CharField(default='Project — Module Ledger', help_text='Header text of the rotating card widget on the hero.', max_length=150)),
                ('ledger_live_label', models.CharField(default='In production', max_length=50)),
            ],
            options={
                'verbose_name': 'Hero Profile',
                'verbose_name_plural': '🏠 Hero Section — Profile',
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('value', models.CharField(help_text="e.g. '6+'", max_length=20)),
                ('label', models.CharField(help_text="e.g. 'Years Experience'", max_length=60)),
            ],
            options={
                'verbose_name': 'Hero Stat',
                'verbose_name_plural': '🏠 Hero Section — Stats',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('tag', models.CharField(help_text="e.g. 'Module 01'", max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Ledger Module (hero widget)',
                'verbose_name_plural': '🏠 Hero Section — Ledger Modules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('label', models.CharField(max_length=60)),
                ('section_anchor', models.SlugField(help_text="The id of the section on the page this should scroll to, e.g. 'about' or 'contact' (no '#').", max_length=60)),
                ('is_cta_button', models.BooleanField(default=False, help_text="Style this link as the highlighted button (usually 'Contact').")),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nav Link',
                'verbose_name_plural': '🧭 Navigation Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Optional — live site or repo link.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': '🚀 Projects',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Your Name — Portfolio', max_length=120)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('brand_initials', models.CharField(default='SG', help_text="Shown in the small logo mark, e.g. 'SG'.", max_length=4)),
                ('brand_name', models.CharField(default='Your Name', max_length=120)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='misc/')),
                ('resume_file', models.FileField(blank=True, help_text="Optional PDF résumé; used by any 'Download résumé' link.", null=True, upload_to='misc/')),
                ('display_font', models.CharField(default='Fraunces', help_text='Used for all headings.', max_length=80)),
                ('display_font_weights', models.CharField(default='300;450;560;650', max_length=120)),
                ('body_font', models.CharField(default='IBM Plex Sans', help_text='Used for paragraph text.', max_length=80)),
                ('body_font_weights', models.CharField(default='400;500;600', max_length=120)),
                ('mono_font', models.CharField(default='IBM Plex Mono', help_text='Used for labels, nav, tags, code-like text.', max_length=80)),
                ('mono_font_weights', models.CharField(default='400;500', max_length=120)),
                ('base_font_size_px', models.PositiveIntegerField(default=16, help_text='Root font size in pixels.')),
                ('color_ink', models.CharField(default='#101C30', max_length=7)),
                ('color_ink_2', models.CharField(default='#17263D', max_length=7)),
                ('color_ink_3', models.CharField(default='#1E304A', max_length=7)),
                ('color_paper', models.CharField(default='#F6F3EA', max_length=7)),
                ('color_paper_2', models.CharField(default='#EEE8D9', max_length=7)),
                ('color_emerald', models.CharField(default='#1F6F5C', max_length=7)),
                ('color_emerald_light', models.CharField(default='#2C8B73', max_length=7)),
                ('color_gold', models.CharField(default='#B8912B', max_length=7)),
                ('color_charcoal', models.CharField(default='#1B1F27', max_length=7)),
                ('color_slate', models.CharField(default='#5B6472', max_length=7)),
                ('color_cream', models.CharField(default='#EDE8DC', max_length=7)),
                ('max_width_px', models.PositiveIntegerField(default=1180)),
                ('section_padding_px', models.PositiveIntegerField(default=112)),
                ('footer_text', models.CharField(default='© 2026 Your Name.', max_length=200)),
                ('footer_tagline', models.CharField(blank=True, default='Built with Django.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': '⚙️ Site Settings (fonts, colours, branding)',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('name', models.CharField(help_text="e.g. 'Backend & Frameworks'", max_length=80)),
                ('slug', models.SlugField(help_text="Used internally to link the tab to its panel, e.g. 'backend'.", max_length=80)),
            ],
            options={
                'verbose_name': 'Skill Category (Tab)',
                'verbose_name_plural': '🧩 Skills — Categories (Tabs)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': '💬 Testimonials',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('text', models.CharField(max_length=300)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='portfolio.experience')),
            ],
            options={
                'verbose_name': 'Experience Bullet Point',
                'verbose_name_plural': 'Experience Bullet Points',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('name', models.CharField(max_length=60)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='portfolio.experience')),
            ],
            options={
                'verbose_name': 'Experience Tech Tag',
                'verbose_name_plural': 'Experience Tech Tags',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('label', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=60)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='portfolio.ledgermodule')),
            ],
            options={
                'verbose_name': 'Ledger Line',
                'verbose_name_plural': 'Ledger Lines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('name', models.CharField(max_length=60)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Tech Tag',
                'verbose_name_plural': 'Project Tech Tags',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('name', models.CharField(max_length=80)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'id'],
            },
        ),
    ]
